### ISSUE TITLE
Error for testing with visualize option

### ISSUE THREAD

**Issue by vietanhle-hri** [vita-epfl/social-nce#11]
I tried to run the test.py script with visualize option `python test.py --policy='sail' --circle --model_file=data/output/imitate-event-data-0.50-weight-2.0-horizon-4-temperature-0.20-nboundary-0/policy_net.pth --visualize` and got an error below

```
Traceback (most recent call last):
  File "test.py", line 126, in <module>
    main()
  File "test.py", line 105, in main
    action = robot.act(ob)
  File "/home/vale/github/mpc-nav/social-nce/crowd_sim/envs/utils/robot.py", line 13, in act
    action = self.policy.predict(state)
  File "/home/vale/github/mpc-nav/social-nce/crowd_nav/policy/sail.py", line 122, in predict
    self.last_state = self.transform(state)
  File "/home/vale/github/mpc-nav/social-nce/crowd_nav/policy/sail.py", line 134, in transform
    num_human = len(state.human_states)
TypeError: object of type 'ObservableState' has no len()
```

Can anyone help me with that issue?

**Comment by YuejiangLIU** [comment]
This is a bit surprising. Were you able to run the code without the `--visualize` option?
